# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJ_DZy491ZhP0g9VfX-xhjJy3UAtYN4e
"""

print("="*40)
print("CIVIL COST ESTIMATOR")
print("="*40)

print("\nPilih Jenis Struktur")
print("1. Balok")
print("2. Kolom")
print("3. Plat")

pilihan = input("Masukkan pilihan (1-3): ")

harga_beton_str = input("\nHarga Beton per m3 (Rp): ")
harga_beton = float(harga_beton_str.replace('.', ''))

if pilihan == "1":
    panjang = float(input("Panjang Balok (m): "))
    lebar = float(input("Lebar Balok (m): "))
    tinggi = float(input("Tinggi Balok (m): "))

    volume = panjang * lebar * tinggi

elif pilihan == "2":
    panjang = float(input("Panjang Kolom (m): "))
    lebar = float(input("Lebar Kolom (m): "))
    tinggi = float(input("Tinggi Kolom (m): "))

    volume = panjang * lebar * tinggi

elif pilihan == "3":
    panjang = float(input("Panjang Plat (m): "))
    lebar = float(input("Lebar Plat (m): "))
    tebal = float(input("Tebal Plat (m): "))

    volume = panjang * lebar * tebal

else:
    print("Pilihan tidak tersedia")
    exit()

biaya = volume * harga_beton

print("\n========== HASIL ==========")
print(f"Volume Beton : {volume:.2f} m3")
print(f"Estimasi Biaya : Rp {biaya:,.0f}")
print("===========================")